export const BARANGAYS = [
  'Alang-Alang',
  'Bakilid',
  'Banilad',
  'Basak',
  'Cabancalan',
  'Cambaro',
  'Canduman',
  'Casili',
  'Casuntingan',
  'Centro',
  'Cubacub',
  'Guizo',
  'Ibabao-Estancia',
  'Jagobiao',
  'Labogon',
  'Lo-oc',
  'Maguikay',
  'Mantuyong',
  'Opao',
  'Pagsabungan',
  'Paknaan',
  'Subangdaku',
  'Tabok',
  'Tawason',
  'Tingub',
  'Tipolo',
  'Umapad',
] as const;

export type Barangay = (typeof BARANGAYS)[number];
